name: elastic_app_search
description: Dart/Flutter package for using Elastic App Search through a simple API returning easy to handle objects
version: 0.4.0-dev.9.9.9.9.9.9.7
repository: https://github.com/julienlebren/elastic_app_search
issue_tracker: https://github.com/julienlebren/elastic_app_search/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^4.0.6
  freezed_annotation: ^2.1.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_map: ^1.1.0
  build_runner: ^2.2.0
  cached_network_image: ^3.2.2
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  latlong2: ^0.8.1

flutter: