name: elastic_app_search
description: Dart/Flutter package for using Elastic App Search through a simple API returning easy to handle objects
version: 0.4.0-dev.9.9.9.9.9.9.1
repository: https://github.com/julienlebren/elastic_app_search
issue_tracker: https://github.com/julienlebren/elastic_app_search/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^4.0.6
  freezed_annotation: ^1.1.0
  html_unescape: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.11
  cached_network_image: ^3.2.0
  freezed: ^1.1.0
  json_serializable: ^6.2.0

flutter: