name: elastic_app_search
description: A new Flutter package project.
version: 0.1.0
repository: https://github.com/julienlebren/elastic_app_search
issue_tracker: https://github.com/julienlebren/elastic_app_search/issues

publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  
flutter: